### PR TITLE
[irods/irods8085] remove ilocate (main)

### PR DESCRIPTION
**Pull request by trel**
need to confirm building... and look through tests...

### CODE REVIEW

**Comment by trel** [comment]
will have to rebase atop #509

**Review by alanking — APPROVED** [review]

**Review by korydraughn — APPROVED** [review]
Excellent.

**Comment by trel** [comment]
confirmed building and packaging succeed on main

**Review by korydraughn — APPROVED** [review]
Pound it.

**Comment by trel** [comment]
rebased, built, and #'d

**Pull request merged**
