### PR TITLE
[irods/irods#7110] iput: Modify -b / -f help text (main)

### PR DESCRIPTION
**Pull request by alanking**
In service of irods/irods#7110

Kind of want to remove that last sentence now that this has been touched by "us". Thoughts?

### CODE REVIEW

**Comment by korydraughn** [comment]
> Kind of want to remove that last sentence now that this has been touched by "us". Thoughts?

What is the motivation behind removing it?

**Comment by trel** [comment]
Oh, yeah, please remove that last sentence.   Speculation, your honor.

**Comment by alanking** [comment]
> The bulk option does work for mounted collections which may represent the quickest way to upload a large number of small files.

A few things...

1. Mentions mounted collections
2. Is this even true?
3. "may"

**Comment by korydraughn** [comment]
Okay. Proceed sir.

**Comment by alanking** [comment]
Done

**Review by korydraughn — APPROVED** [review]
Pound/Merge when ready.

**Pull request merged**
