### PR TITLE
[irods/irods#7376] imeta: add set_ips_display_name call (main)

### PR DESCRIPTION
**Pull request by mstfdkmn**
This will display the command name alongside the connection information (spOption).

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Looks good to me.

**Comment by alanking** [comment]
@mstfdkmn - Just noting that the email address used for the Author field of your commit is not linked to your GitHub account. Please let us know if this is intentional.

**Review by korydraughn — APPROVED** [review]

**Comment by mstfdkmn** [comment]
> @mstfdkmn - Just noting that the email address used for the Author field of your commit is not linked to your GitHub account. Please let us know if this is intentional.

No, that was not intentional. I guess it is because of the fact that my local (a vm to test the change) is not configured properly.

**Comment by trel** [comment]
Correct - you can force push the single commit - or let us know your preferred email address.

**Comment by korydraughn** [comment]
Looks good.

**Comment by trel** [comment]
I only see the updated email on the commit line, not the author line.

and we need an empty line between the commit title and rest of the commit message

**Comment by alanking** [comment]
We did it. Please eyeball.

**Comment by trel** [comment]
ship it

**Pull request merged**
