### PR TITLE
[#7761] Fix help text for itree JSON option (4-3-stable)

### PR DESCRIPTION
**Pull request by korydraughn**
This doesn't require testing. It's just help text.

I opened an issue for test coverage. See irods/irods#7825. We'll handle that post 4.3.3.

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Well, it requires test insofar as you've confirmed that `-J` performs the function that `-j` was previously thought to have been performing, right? If so, let's put this in.

**Comment by alanking** [comment]
Okay. I say we add #s.

**Comment by korydraughn** [comment]
#'d

**Comment by trel** [comment]
ew.  don't like that it's a capital.

but here we are.

**Pull request merged**
