### PR TITLE
[irods/irods_6223] add inputFile size limit to irule help text (4-3-stable)

### PR DESCRIPTION
**Pull request by trel**
and some other rewording from 'line' to 'part'

### CODE REVIEW

**Review by alanking — APPROVED** [review]
Seems good to me. Maybe we get thoughts from one more person on this one before we put it in...

**Comment by trel** [comment]
built and 'tested' via `irule -h` and looking at the words.

**Review by korydraughn — APPROVED** [review]
Reads fine.

I think what would help this documentation is actual examples of the different forms of input.

That can come later though. The objective of this PR is satisfied IMO.

**Comment by trel** [comment]
I see - we have a number of them in the examples linked... but yes, I agree.

**Comment by trel** [comment]
#'d.

**Pull request merged**
