### PR TITLE
[irods#6740] shaping up iqstat (main)

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Review by korydraughn — COMMENTED** [review]
Code looks good.

Have you tested this PR or 4-3-stable?

**Comment by d-w-moore** [comment]
@korydraughn my understanding (based on @alanking 's advice) was not to worry about testing on `4-3-stable`, since it's basically `main`. But I don't mind running it there, if you'd like.

**Comment by korydraughn** [comment]
Sorry for the confusion, I was saying the same thing as @alanking.

Basically, have you tested these changes for either branch?

**Comment by d-w-moore** [comment]
@korydraughn  - No problem, I scanned "... or 4-3-stable" as "... for 4-3-stable",  sorry about that.  I'm sure I did test for `4-2-stable` and  `main`, and all tests passed. But I'm going to go ahead with another.  It can't hurt : )

**Comment by d-w-moore** [comment]
Ok - all tests passed excepet for  TEST-irods.test.test_resource_types.Test_Resource_ReplicationToTwoCompoundResourcesWithPreferArchive, and that log contained no "FAILED TESTING ASSERTION", only `Unexpected output on stderr` (and none of those involve **iqstat**).

**Comment by alanking** [comment]
I think that's okay. That suite has at least one known intermittent failure. See https://github.com/irods/irods/issues/6058

**Review by alanking — APPROVED** [review]
Looks good. Please to #

---

Cherry-picked from https://github.com/irods/irods_client_icommands/pull/349

**Comment by d-w-moore** [comment]
Now with more `#`

**Pull request merged**
