### PR TITLE
[irods/irods#5220] cmake: use GNUInstallDirs (master)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses irods/irods#5220 for this repository.

Will wait for feedback before pushing through Jenkins.

### CODE REVIEW

**Comment by trel** [comment]
any way to reuse/share the cmake/InstallDirs.cmake from main irods/irods?    no worries, it's not big, but if it's identical...

is that a bad idea?      

please run through CI

**Comment by SwooshyCueb** [comment]
Since the icommands are designed to be built without the irods sources present, the only practical way I know of to do this is to install `InstallDirs.cmake` into the install prefix somewhere and maybe point to it in one of the `lib/irods/cmake` files. Considering how small it is, it's probably more trouble than it's worth, at least for the time being.

**Comment by trel** [comment]
Agreed.   Trying to get them decoupled AND not duplicate code are sometimes competing interests...

**Comment by trel** [comment]
Don't we already use some CMake magic from the irods-dev package?    We can add to the magic?

**Comment by trel** [comment]
yes, looking very nice.

**Pull request merged**
