### PR TITLE
Allow quoted arguments in imeta interactive mode (master)

### PR DESCRIPTION
**Pull request by d-w-moore**

### CODE REVIEW

**Comment by trel** [comment]
seems good - this works with the test to prove it stays in the console/prompt?

**Comment by d-w-moore** [comment]
Yes, the test passed with that included.

Daniel Moore
Applications Engineer
iRODS Consortium, RENCI, UNC Chapel Hill
(919) 445-9616

________________________________

**Comment by trel** [comment]
gotcha - please (squash? and) # em.

**Comment by d-w-moore** [comment]
Also, "imeta>" prints exactly once despite multiple inputs if the terminal is not a tty... so that part of this and other tests passed as well.  I thought Cyverse and others might think it strange to see the "imeta>" prompt repeating endlessly on stdout with potentially noone listening....

**Comment by trel** [comment]
seems reasonable - use case is pushing a file of commands into imeta, right?

**Comment by d-w-moore** [comment]
Yes, `cat`ting a file of sub commands in through stdin as Tony was doing in https://github.com/irods/irods/issues/5518

**Comment by trel** [comment]
indeed.   so yes, one or two commits is fine - # em up.

**Pull request merged**
