### PR TITLE
avoid USER_INCOMPATIBLE_PARAMS in Phymv rule file test

### PR DESCRIPTION
**Pull request by d-w-moore**
corequisite with PR: https://github.com/irods/irods/pull/6170
(issue: https://github.com/irods/irods/issues/6169)

### CODE REVIEW

**Comment by trel** [comment]
looks good - yes please link to 6169 in commit message

**Comment by d-w-moore** [comment]
passed test, so will add [# 6169] to first commit - and perhaps refer to both 6169 and 4409 on the second one?

**Comment by trel** [comment]
maybe 'remove' rather than 'torch'.

**Comment by d-w-moore** [comment]
done and #'d

**Pull request merged**
