### PR TITLE
[irods/irods#5875] Update userspace packager inclusion directives

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Solves irods/irods#5875 by including libcurl-gnutls and its dependency tree in the inclusion directives for bionic.
An exclusion directive for libcurl was added to centos 7 as it is installed by default.

Additionally, the directive file for xenial was removed as the packager for master does not support xenial.

### CODE REVIEW

**Comment by trel** [comment]
this separation of concerns is pleasing to me.

**Comment by SwooshyCueb** [comment]
\#'d

**Comment by SwooshyCueb** [comment]
okay *now* it's \#'d

**Comment by trel** [comment]
two commits - only one has the #

**Comment by trel** [comment]
so squash or add another, either is fine

**Comment by SwooshyCueb** [comment]
Squashed

**Pull request merged**
