### PR TITLE
itouch v2 (master)

### PR DESCRIPTION
**Pull request by korydraughn**
Depends on the **touch** API plugin defined in this [PR](https://github.com/irods/irods/pull/5147).

Passes itouch tests.

### CODE REVIEW

**Comment by trel** [comment]
so this supersedes #150 and it should be closed without merging... right?

**Comment by korydraughn** [comment]
yes

**Comment by korydraughn** [comment]
i left the other one in place in case someone wanted to discuss it.

**Comment by korydraughn** [comment]
Added #

**Pull request merged**
