### PR TITLE
avoid USER_INCOMPATIBLE_PARAMS in Phymv rule file test (4-2-stable)

### PR DESCRIPTION
**Pull request by d-w-moore**
corequisite with PR: https://github.com/irods/irods/pull/6206
(issue: https://github.com/irods/irods/issues/6169)

### CODE REVIEW

**Comment by trel** [comment]
looks good - yes please link to 6169 in commit message

**Comment by d-w-moore** [comment]
passed test, so will # then, yes ?

**Comment by trel** [comment]
update the commit message, without the #, first.

**Comment by trel** [comment]
good good, please #

**Comment by d-w-moore** [comment]
done!

**Pull request merged**
