### PR TITLE
[#7488] Deprecate "imeta lsw" (main)

### PR DESCRIPTION
**Pull request by korydraughn**
The body of the commit message is derived from the addw/rmw deprecation commit messages.

### CODE REVIEW

**Comment by trel** [comment]
change looks good.    nowhere else needs a note?

**Comment by korydraughn** [comment]
That's the only change made for the addw/rmw commands. I didn't see any other changes for the deprecation step.

**Comment by korydraughn** [comment]
I thought we may have returned a deprecation error code via the rError stack, but I didn't see any changes for that.

**Comment by trel** [comment]
Fair enough.   Notice is given in the release notes as well.

**Review by alanking — COMMENTED** [review]
I know it's just what we did for `addw` and `rmw`, but we *could* put a "Deprecated" note next to the listings of the subcommands in the listings under "Commands are:" as well as the detailed description yieled by, e.g. `imeta h lsw`. Up to you

**Comment by korydraughn** [comment]
Sure, that works.

**Comment by korydraughn** [comment]
Updated other help sections to include words about deprecation of the wildcard commands.

**Review by alanking — APPROVED** [review]
Looks good to me. Squash and #, I say. Don't forget that this PR is not in the irods/irods repo so that will need to be in the commit message in order for the issue to link correctly

**Comment by korydraughn** [comment]
#'d

**Pull request merged**
