### PR TITLE
[#6128][#6127] Prevent rodsadmins from downgrading each others' user type

### PR DESCRIPTION
**Pull request by phdavis1027**
#6128 #6127 Previously, rodsadmin users could downgrade the user types of other rodsadmins, including themselves. This PR checks on the client side whether the target user of an ```iadmin moduser``` command is themselves a rodsadmin and throws SYS_NOT_ALLOWED if an attempt is being made to downgrade them.

### CODE REVIEW

**Comment by korydraughn** [comment]
iRODS supports many clients. However, this change only affects the icommands. We need to apply a change that solves the problem for all clients. That means the problem must be addressed from within the server.

**Comment by trel** [comment]
What Kory said... but also, this is not just checking whether the target user is a rodsadmin - it's whether the target rodsadmin is the current user OR the target user is a rodsadmin that is running an iRODS server in this zone.

If the target user is a rodsadmin who is both different from the logged-in user AND not running an iRODS server, then it can / should be downgraded.

**Comment by phdavis1027** [comment]
> What Kory said... but also, this is not just checking whether the target user is a rodsadmin - it's whether the target rodsadmin is the current user OR the target user is a rodsadmin that is running an iRODS server in this zone.
> 
> If the target user is a rodsadmin who is both different from the logged-in user AND not running an iRODS server, then it can / should be downgraded.

I think the "running an iRODS server" distinction was not clear to me. In a Zone Report for instance, the user running a server will be the username listed under ```zone_report[icat_server][service_account_environment][irods_user_name]``` ( or ```zone_report[servers][<some index to particular server>][service_account_environment][irods_user_name]```)?

**Comment by trel** [comment]
Yes, I believe that is correct.  So build a set of usernames from that, plus the current user, and then check the set.

**Comment by korydraughn** [comment]
Yes, `zone_report...[service_account_environment][irods_user_name]` should match the `irods_user_name` in /var/lib/irods/.irods/irods_environment.json.

**Pull request closed without merging**
