### PR TITLE
[irods/irods#6597] Base libssl on OpenSSL version (main)

### PR DESCRIPTION
**Pull request by alanking**
The libssl declared dependency in the packaging step needs to be conditionally set based on the version of OpenSSL found by find_package.

---

Companion PR: https://github.com/irods/irods/pull/6620

### CODE REVIEW

**Comment by korydraughn** [comment]
Based on what I've read about the OpenSSL compatibility macro, it's not needed in this repo because icommands don't indirectly include any OpenSSL headers.

Correct?

**Comment by alanking** [comment]
> Based on what I've read about the OpenSSL compatibility macro, it's not needed in this repo because icommands don't indirectly include any OpenSSL headers.
> 
> Correct?

Yes, that's right. No OpenSSL calls or types are referenced directly in this repo.

**Review by korydraughn — APPROVED** [review]

**Comment by alanking** [comment]
Rebased and marking Ready for Review.

**Review by korydraughn — APPROVED** [review]
Still looks good to me.

**Comment by alanking** [comment]
Now that https://github.com/irods/externals/pull/178 is merged, I think this is ready.

**Pull request merged**
