### PR TITLE
[irods/irods#4481] Updated help text for "iadmin suq" (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Comment by trel** [comment]
seem good upon inspection.

**Comment by korydraughn** [comment]
I avoided explained how `sgq` can be used to simulate user quotas because that is not the responsibility of the help text.

docs.irods.org is a better place for that.

**Comment by trel** [comment]
right - thought through that - i think your edits are clean enough.   if the tests are passing - ship em.

**Review by alanking — APPROVED** [review]

**Comment by korydraughn** [comment]
All core tests pass.

#'d

**Pull request merged**
