### PR TITLE
[irods/irods#5479] Add new PAM iinit flow (main)

### PR DESCRIPTION
**Pull request by alanking**
companion PR for irods/irods#6358

Keeping as draft until proper testing is completed

### CODE REVIEW

**Comment by alanking** [comment]
Still think `iinit` will need some TLC after all this, but this will at least ensure that the new flow for PAM is being handled.

**Review by korydraughn — COMMENTED** [review]
Code looks fine.

Any concerns?

Based on the comments in the companion irods/irods PR, I take it you're addressing test failures related to this change?

**Comment by alanking** [comment]
Right, still working on test failures. I think I've found the problem area in the companion PR.

**Comment by korydraughn** [comment]
Cool cool.

Will await results of your finding before marking as approved.

**Comment by alanking** [comment]
All tests passed

**Review by korydraughn — APPROVED** [review]

**Pull request merged**
