### PR TITLE
Added option to enable Address Sanitizer (main)

### PR DESCRIPTION
**Pull request by korydraughn**

### CODE REVIEW

**Review by alanking — COMMENTED** [review]
Seems like we may still be working through some things with this change?
https://github.com/irods/irods/pull/6673/files#r1009870794

Otherwise, looks good to me. I'll poke the Markus to have a look as well

**Comment by korydraughn** [comment]
Hit a compilation issue when ASan is enabled.
```bash
$ ~/dev/prog/cpp/build_icommands $ ninja package
[201/203] generating manpage itree.1
FAILED: man/itree.1 /home/kory/dev/prog/cpp/build_icommands/man/itree.1 
cd /home/kory/dev/prog/cpp/build_icommands && /opt/irods-externals/cmake3.21.4-0/bin/cmake -E env LD_LIBRARY_PATH=/usr/lib: /usr/bin/help2man -h -h -N -n an\ iRODS\ iCommand --version-string="iRODS-4.3.0" /home/kory/dev/prog/cpp/build_icommands/itree -o /home/kory/dev/prog/cpp/build_icommands/man/itree.1
help2man: can't get `-h' info from /home/kory/dev/prog/cpp/build_icommands/itree
Try `--no-discard-stderr' if option outputs to stderr
ninja: build stopped: subcommand failed.
```

**Comment by trel** [comment]
`itree -h` works for me?

**Comment by korydraughn** [comment]
Me too, but something is not happy when ASan is enabled during compilation.

**Comment by korydraughn** [comment]
Compiling with ASan uncovered a memory issue in `itree -h` which causes packaging to fail.

I'll try swizzling the order of things to get around the ASan issue.

**Comment by korydraughn** [comment]
Packaging now succeeds so I think we're good now.

Will add the pounds if there are no objections.

**Comment by korydraughn** [comment]
@trel I've updated the error message.

**Comment by trel** [comment]
good good - rest seems fine to me.

**Review by alanking — APPROVED** [review]

**Comment by korydraughn** [comment]
Added #'s

**Review by alanking — APPROVED** [review]

**Pull request merged**
