### PR TITLE
 Catching exceptions and ensuring clients disconnect (4-2-stable)

### PR DESCRIPTION
**Pull request by alanking**
Addresses https://github.com/irods/irods/issues/6068
Addresses https://github.com/irods/irods/issues/6365
Addresses https://github.com/irods/irods/issues/6390

Companion PR: https://github.com/irods/irods/pull/6840

Cherry-picked and adapted from #342

### CODE REVIEW

**Review by korydraughn — APPROVED** [review]
Looks fine to me. If the tests pass, then ship it.

**Comment by korydraughn** [comment]
This still looks fine.

Are we waiting on the PR in irods/irods?

**Comment by alanking** [comment]
Yes, waiting on #6840, which is waiting on #6844, which is waiting on test results (almost done, and passing)

**Comment by alanking** [comment]
#'d

**Comment by korydraughn** [comment]
Merge when ready.

**Pull request merged**
