### PR TITLE
itrim: Note deprecated options (main)

### PR DESCRIPTION
**Pull request by alanking**
In service of irods/irods#7502
In service of irods/irods#7498

Companion PR: irods/irods#7500

### CODE REVIEW

**Comment by alanking** [comment]
Changed issue number on -N deprecation to #7502.

**Comment by korydraughn** [comment]
I take it this is so everything is in sync?

**Comment by korydraughn** [comment]
By **everything**, I mean the main branch and the 4-3-stable branch.

**Comment by alanking** [comment]
I think so, if I get your meaning.

We want the deprecation to be reflected in 4.3.2 as it has been deprecated in the 4-2-stable branch since 4.2.8. We just didn't cherry-pick it to main (or 4-3-stable) because I think we thought -N would be removed by now, not knowing the impact such a change would have on the API.

Also, noticed that the "DEPRECATED" label in 4.2.12 is not as... enthusiastic. :) Will replace "(DEPRECATED") with "[Deprecated]" to match the 4.2 series.

**Comment by alanking** [comment]
Updated the notes to be less yell-y.

**Comment by trel** [comment]
love it.

**Review by korydraughn — APPROVED** [review]
Looks good to me.

Pound when ready.

**Pull request merged**
