### PR TITLE
[irods/irods_testing_jenkins#116] "gzip -k" alternative for CentOS 7 (master)

### PR DESCRIPTION
**Pull request by korydraughn**
For more info, see https://github.com/irods/irods_testing_jenkins/issues/116

### CODE REVIEW

**Comment by korydraughn** [comment]
@SwooshyCueb Any concerns around these changes?

**Review by SwooshyCueb — APPROVED** [review]
I typically try to avoid using anything that requires a shell in cmake, but if you've tested this and it works fine, I've got no issue merging this.

**Comment by korydraughn** [comment]
added #

**Comment by trel** [comment]
Yes, this doesn't add a new shell command... just manipulates one we've already got.

Removing shell is the future... but not today.

**Comment by SwooshyCueb** [comment]
> Yes, this doesn't add a new shell command... just manipulates one we've already got.

What I mean to say is that I try to avoid assuming this kind of stuff runs in a shell to begin with vs being executed directly (`execvp` style) by make or ninja or whathaveyou.
But again, I'm okay with this being merged if it's been tested.

**Pull request merged**
