### PR TITLE
[irods/irods#5081] imeta interactive: do not exit on error status from do_command (master)

### PR DESCRIPTION
**Pull request by SwooshyCueb**
Addresses irods/irods#5081

### CODE REVIEW

**Comment by trel** [comment]
seems pretty straightforward.

an error from imeta will now be printed, but not make imeta exit, is that correct?

**Comment by SwooshyCueb** [comment]
That's correct. The only return value from do_command that will cause an exit is `-1`, which is what's returned on the `quit` command.

**Comment by trel** [comment]
excellent.   please # em.

**Comment by SwooshyCueb** [comment]
All tests passed except the one that doesn't. #s added

**Pull request merged**
